name: Generate Example

on:
  push:
    branches:
      - main
jobs:
  generate-example:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Run the server
        run: |
          go run . &

      - name: Wait for the server
        run: |
          until curl -s http://localhost:8080/ > /dev/null 2>&1; do
            sleep 1
          done

      - name: Generate the example
        run: |
          curl http://localhost:8080/?options=Red,Green,Blue\&target=0\&fps=24\&duration=5 > example.gif

      - name: Commit and push the example
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          add: "example.gif"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
