name: Run and Get Example

on:
  push:
    branches:
      - main
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: run server
        run: |
          go run . &

      - name: wait for server
        run: |
          until curl -sSf http://localhost:8080/health; do
            sleep 1
          done

      - name: request the example
        run: |
          curl -m 5 http://localhost:8080/?options=Red,Green,Blue\&target=0\&fps=24\&duration=10 > example.gif

      - name: commit and push example
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          add: "example.gif"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
